/**
 * Web CSS-variable generation from the platform-neutral tokens. The admin app imports
 * the generated stylesheet so web renders the exact same design primitives as mobile.
 */
import {
  createColorTokens,
  spacing,
  radius,
  borderWidth,
  iconSize,
  type ColorScheme,
} from './index';

function toKebab(key: string): string {
  return key.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function colorVars(scheme: ColorScheme, accent?: string): string {
  const colors = createColorTokens(accent)[scheme];
  return Object.entries(colors)
    .map(([key, value]) => `  --color-${toKebab(key)}: ${value};`)
    .join('\n');
}

function scaleVars(prefix: string, scale: Record<string, number>): string {
  return Object.entries(scale)
    .map(([key, value]) => `  --${prefix}-${toKebab(key)}: ${value}px;`)
    .join('\n');
}

/** Builds a full CSS stylesheet with light defaults + dark overrides. */
export function generateTokensCss(accent?: string): string {
  const nonColor = [
    scaleVars('space', spacing),
    scaleVars('radius', radius),
    scaleVars('border', borderWidth),
    scaleVars('icon', iconSize),
  ].join('\n');

  return `/* Generated by @soliton/design-tokens — do not edit by hand. */
:root {
${colorVars('light', accent)}
${nonColor}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${colorVars('dark', accent)}
  }
}

:root[data-theme='dark'] {
${colorVars('dark', accent)}
}
`;
}
